when:
  - event: deployment

depends_on:
  - check-version
  - headless-tests-deployment
  - headless-tests-interpreter-deployment
  - slow-headless-tests
  - slow-headless-tests-interpreter
  - headed-tests

steps:
  - name: deploy
    image: zacharyspector/elide:latest
    pull: true
    entrypoint: ["/bin/sh", "release.sh"]