when:
  - event: deployment

depends_on:
  - check-version
  - headless-tests-deployment
  - headless-tests-interpreter-deployment
  - headed-tests

steps:
  - name: deploy
    image: zacharyspector/elide:latest
    pull: true
    entrypoint: ["/bin/bash", "release.sh"]
    environment:
      CODEBERG_USERNAME:
        from_secret: CODEBERG_USERNAME
      CODEBERG_PASSWORD:
        from_secret: CODEBERG_PASSWORD
      PYPI_USERNAME:
        from_secret: PYPI_USERNAME
      PYPI_PASSWORD:
        from_secret: PYPI_PASSWORD