when:
  - event: deployment

depends_on:
  - headless-tests
  - headless-tests-interpreter
  - headed-tests

steps:
  - name: check_version
    image: python:3.12
    steps:
      - python check_version.py
  - name: deploy
    image: zacharyspector/elide:latest
    pull: true
    entrypoint: ["/bin/sh", "release.sh"]