when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

matrix:
  DATABASE:
    - not parquetdb and not sqlite
    - parquetdb
  EXECUTION:
    - thread_workers
    - process_workers
    - not thread_workers and not process_workers and not interpreter_workers
  MANAGER:
    - not process_manager and not thread_manager and not interpreter_manager
    - thread_manager

steps:
  - name: headless
    image: zacharyspector/elide:latest
    pull: true
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - DATABASE="${DATABASE}"
      - export DATABASE
      - TOXFILE=lisien/tox.ini
      - python -m pip install --root-user-action ignore pytest tox lisien/
      - PYTEST_KEYWORDS="not slow and not big and $DATABASE and ${EXECUTION} and ${MANAGER}"
      - export PYTEST_KEYWORDS
      - echo "will run $PYTEST_KEYWORDS"
      - tox run-parallel -c $TOXFILE
