when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

matrix:
  PYTHON_VERSION:
    - 3.12
    - 3.13
    - 3.14

variables:
  - &stepname headed_${PYTHON_VERSION}

steps:
  - name: *stepname
    image: zacharyspector/elide:latest
    pull: true
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - DISPLAY=:0
      - echo "DISPLAY=$DISPLAY"
      - export DISPLAY
      - Xvfb $DISPLAY &
      - PYTHON=python${PYTHON_VERSION}
      - echo "PYTHON=$PYTHON"
      - PYTHONPATH="$PWD/lisien:$PWD/elide"
      - echo "PYTHONPATH=$PYTHONPATH"
      - export PYTHONPATH
      - python -m pytest -svvx elide/elide/tests