when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

matrix:
  DATABASE:
    - not parquetdb and not sqlite
    - sqlite
    - parquetdb
    - prerelease-parquetdb
  EXECUTION:
    - thread
    - process
    - interpreter
    - not thread and not process and not interpreter

variables:
  - &python_image python:3.14
  - &headless_name headless_3.14
  - &slow_headless_name slow_headless_3.14

steps:
  - name: *headless_name
    image: *python_image
    pull: true
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m venv .venv
      - . .venv/bin/activate
      - python -m pip install --upgrade pip
      - python -m pip install lisien/
      - python -m pip install pytest
      - if [ "${DATABASE}" = 'prerelease-parquetdb' ]; then
      - DATABASE=parquetdb
      - export DATABASE
      - python -m pip install git+https://github.com/lllangWV/ParquetDB.git@bcc6613d2d552ece646c4628a514b43c381d2bc6
      - else
      - DATABASE="${DATABASE}"
      - export DATABASE
      - fi
      - pytest -vvx -k "not slow and not big and $DATABASE and ${EXECUTION}" lisien/lisien/tests
  - name: *slow_headless_name
    image: *python_image
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m venv .venv${PYTHON_VERSION}
      - . .venv${PYTHON_VERSION}/bin/activate
      - python -m pip install --upgrade pip
      - python -m pip install pytest
      - python -m pip install lisien/
      - if [ "${DATABASE}" = 'prerelease-parquetdb' ]; then
      - DATABASE=parquetdb
      - export DATABASE
      - python -m pip install git+https://github.com/lllangWV/ParquetDB.git@bcc6613d2d552ece646c4628a514b43c381d2bc6
      - else
      - DATABASE="${DATABASE}"
      - export DATABASE
      - fi
      - python -m pytest -vvx -k "slow or big and $DATABASE and ${EXECUTION}" lisien/lisien/tests
