when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

matrix:
  PYTHON_VERSION:
    - 3.12
    - 3.13
    - 3.14
  DATABASE:
    - not parquetdb and not sqlite
    - sqlite
    - parquetdb

steps:
  - name: headless_${PYTHON_VERSION}
    image: python:${PYTHON_VERSION}
    pull: true
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m venv .venv
      - . .venv/bin/activate
      - python -m pip install --upgrade pip
      - python -m pip install lisien/
      - python -m pip install pytest
      - pytest -vvx -k "not slow and not big and not subinterpreter and ${DATABASE}" lisien/lisien/tests
