when:
  - event: push
    branch: main

steps:
  - name: headed
    image: zacharyspector/elide:latest
    pull: true
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - DISPLAY=:0
      - echo "DISPLAY=$DISPLAY"
      - export DISPLAY
      - Xvfb $DISPLAY &
      - python -m pip wheel lisien/
      - mv lisien-*.whl /wheels/lisien-0.0.0.dev0-py3-none-any.whl
      - tox run-parallel -c elide/tox.ini