when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

steps:
  - name: headed
    image: zacharyspector/elide:latest
    pull: true
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m pip wheel --no-deps lisien/
      - mv lisien-*.whl /wheels/lisien-0.0.0.dev0-py3-none-any.whl
      - for minor in $(seq 12 14); do Xvfb -once :$minor & done;
      - tox run-parallel -o -c elide/tox.ini
