when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

matrix:
  PYTHON_VERSION:
    - 3.12
    - 3.13
    - 3.14

variables:
  - &stepname headed_${PYTHON_VERSION}

steps:
  - name: *stepname
    image: zacharyspector/elide:latest
    pull: true
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - DISPLAY=:0
      - echo "DISPLAY=$DISPLAY"
      - export DISPLAY
      - Xvfb $DISPLAY &
      - PYTHON=python${PYTHON_VERSION}
      - echo "PYTHON=$PYTHON"
      - $PYTHON -m venv --system-site-packages .venv
      - . .venv/bin/activate
      - echo "python=$(which python)"
      - python -m pip install --upgrade pip
      - python -m pip install pytest lisien/ elide/
      - python -m pytest -vvx elide/elide/tests