when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

matrix:
  DATABASE:
    - not parquetdb and not sqlite
    - sqlite
    - parquetdb
    - prerelease-parquetdb
  MANAGER:
    - not process_manager and not thread_manager and not interpreter_manager
    - process_manager
    - thread_manager
    - interpreter_manager

variables:
  - &python_image python:3.14
  - &headless_name headless_3.14

steps:
  - name: *headless_name
    image: *python_image
    pull: true
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m venv .venv
      - . .venv/bin/activate
      - if [ "${DATABASE}" = 'prerelease-parquetdb' ]; then
      - DATABASE=parquetdb
      - TOXFILE=lisien/tox_prerelease_parquetdb.ini
      - export DATABASE
      - else
      - DATABASE="${DATABASE}"
      - TOXFILE=lisien/tox.ini
      - export DATABASE
      - fi
      - PYTEST_KEYWORDS="not slow and not big and interpreter_workers and $DATABASE and ${MANAGER}"
      - echo "will run $PYTEST_KEYWORDS"
      - tox run -c $TOXFILE
