when:
  - event: push
    branch: main

steps:
  - name: headless3.12
    image: python:3.12
    commands:
      - python -V
      - python -m pip install tox
      - tox -c lisien/tox.ini -e py312
  - name: headless3.13
    image: python:3.13
    commands:
      - python -V
      - python -m pip install tox
      - tox -c lisien/tox.ini -e py313
  - name: headless3.14
    image: python:3.14
    commands:
      - python -V
      - python -m pip install tox
      - tox -c lisien/tox.ini -e py314

depends_on:
  - venv312
  - venv313
  - venv314
