when:
  - branch: main

steps:
  - name: headless3.12
    image: python:3.12
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - source .venv312/bin/activate
      - tox -c lisien/tox.ini -e py312
  - name: headless3.13
    image: python:3.13
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - source .venv313/bin/activate
      - tox -c lisien/tox.ini -e py313
  - name: headless3.14
    image: python:3.14
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - source .venv314/bin/activate
      - tox -c lisien/tox.ini -e py314

depends_on:
  - venv312
  - venv313
  - venv314
