when:
  - event: push
    branch: opttest

steps:
  - name: venv
    image: python:3.12
    commands:
      - python -m venv .venv312
      - . .venv312/bin/activate
      - python -m pip install --upgrade pip
      - python -m pip install tox
  - name: slow_headless3.12
    image: python:3.12
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - . .venv312/bin/activate
      - tox -c lisien/tox_slow.ini -e py312
  - name: big_headless3.12
    image: python:3.12
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - . .venv312/bin/activate
      - tox -c lisien/tox_big.ini -e py312