when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

depends_on:
  - headless-tests.yaml

matrix:
  PYTHON_VERSION:
    - 3.12
    - 3.13
    - 3.14
  DATABASE:
    - parquetdb

steps:
  - name: prerelease_parquetdb_headless_${PYTHON_VERSION}
    image: python:${PYTHON_VERSION}
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m venv .venv
      - . .venv/bin/activate
      - python -m pip install --upgrade pip
      - python -m pip install tox
      - TOX_ENV_LIST=$(echo "${PYTHON_VERSION}" | sed -Ee 's/([0-9])\.([0-9]{2}).*/py\1\2/')
      - echo "TOX_ENV_LIST=$TOX_ENV_LIST"
      - PYTEST_KEYWORDS="not slow and not big and not subinterpreter and ${DATABASE}"
      - echo "PYTEST_KEYWORDS=$PYTEST_KEYWORDS"
      - export PYTEST_KEYWORDS
      - tox run -c lisien/tox.ini -e $TOX_ENV_LIST
