when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

depends_on:
  - headless-tests

matrix:
  PYTHON_VERSION:
    - 3.12
    - 3.13
    - 3.14
  DATABASE:
    - parquetdb

variables:
  - &python_image python:${PYTHON_VERSION}
  - &headless_name prerelease_parquetdb_headless_${PYTHON_VERSION}

steps:
  - name: *headless_name
    image: *python_image
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m venv .venv
      - . .venv/bin/activate
      - python -m pip install --upgrade pip
      - python -m pip install git+https://github.com/lllangWV/ParquetDB.git@bcc6613d2d552ece646c4628a514b43c381d2bc6
      - python -m pip install lisien/
      - python -m pip install pytest
      - pytest -vvx -k "not slow and not big and not subinterpreter and ${DATABASE}" lisien/lisien/tests
