matrix:
  DATABASE:
    - not parquetdb and not sqlite
    - sqlite
    - parquetdb
    - prerelease-parquetdb
  MANAGER:
    - not process_manager and not thread_manager and not interpreter_manager
    - process_manager
    - thread_manager
    - interpreter_manager

variables:
  - &python_image python:3.14
  - &slow_headless_name slow_headless_3.14

steps:
  - name: *slow_headless_name
    image: *python_image
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m venv .venv${PYTHON_VERSION}
      - . .venv${PYTHON_VERSION}/bin/activate
      - if [ "${DATABASE}" = 'prerelease-parquetdb' ]; then
      - DATABASE=parquetdb
      - export DATABASE
      - TOXFILE=lisien/tox_prerelease_parquetdb
      - else
      - DATABASE="${DATABASE}"
      - export DATABASE
      - TOXFILE=lisien/tox.ini
      - fi
      - python -m pip install pytest lisien/
      - PYTEST_KEYWORDS="(slow or big) and interpreter_workers and $DATABASE"
      - echo "will run $PYTEST_KEYWORDS"
      - tox run -c $TOXFILE
