when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

depends_on:
  - headless-tests

matrix:
  PYTHON_VERSION:
    - 3.12
    - 3.13
    - 3.14

steps:
  - name: headless_slow_${PYTHON_VERSION}
    image: python:${PYTHON_VERSION}
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m venv .venv${PYTHON_VERSION}
      - . .venv${PYTHON_VERSION}/bin/activate
      - python -m pip install --upgrade pip
      - python -m pip install tox
      - TOX_ENV_LIST=$(echo "${PYTHON_VERSION}" | sed -Ee 's/([0-9])\.([0-9]{2})/py\1\2/')
      - echo "TOX_ENV_LIST=$TOX_ENV_LIST"
      - tox run -c lisien/tox.ini