when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

depends_on:
  - prerelease-parquetdb-headless-tests

matrix:
  PYTHON_VERSION:
    - 3.12
    - 3.13
    - 3.14

steps:
  - name: headless_slow_${PYTHON_VERSION}
    image: python:${PYTHON_VERSION}
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m venv .venv${PYTHON_VERSION}
      - . .venv${PYTHON_VERSION}/bin/activate
      - python -m pip install --upgrade pip
      - python -m pip install pytest
      - python -m pip install lisien/
      - python -m pytest -vvx -k 'slow or big' --pyargs lisien.tests