when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

depends_on:
  - slow-headless-tests

steps:
  - name: headless_subinterpreter_3.14
    image: python:3.14
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m venv .venv
      - . .venv/bin/activate
      - python -m pip install --upgrade pip
      - python -m pip install lisien/
      - python -m pip install pytest
      - python -m pytest -vvx -k subinterpreter lisien/lisien/tests