when:
  - event: push
    branch: main
  - event: pull_request
    repo: clayote/Lisien

depends_on:
  - slow-headless-tests

steps:
  - name: headless_subinterpreter_3.14
    image: python:3.14
    commands:
      - TMPDIR=$(python find_ramdisk.py)
      - echo "TMPDIR=$TMPDIR"
      - export TMPDIR
      - python -m venv .venv${PYTHON_VERSION}
      - . .venv${PYTHON_VERSION}/bin/activate
      - python -m pip install --upgrade pip
      - python -m pip install tox
      - PYTEST_KEYWORDS=subinterpreter
      - echo "PYTEST_KEYWORDS=$PYTEST_KEYWORDS"
      - export PYTEST_KEYWORDS
      - tox run -c lisien/tox_terp.ini